# Generated by Django 4.2.2 on 2023-06-18 07:07

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Soil',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('airhum', models.CharField(max_length=10)),
                ('sun', models.CharField(max_length=10)),
                ('soilhum', models.CharField(max_length=10)),
                ('temp', models.CharField(max_length=10)),
            ],
        ),
    ]
